/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera, PerspectiveCamera } from "@react-three/drei";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline("https://prod.spline.design/KrZksOZWrKg2VZ2f/scene.splinecode");
  return (
    <>
      <color attach="background" args={["#352357"]} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <PerspectiveCamera name="Camera" makeDefault={true} far={100000} near={70} fov={45} up={[0, 1, 0]} position={[145.05, 215.91, -170.2]} rotation={[-2.39, 0.65, 2.63]} scale={1} />
          <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials["Cube Material"]} castShadow receiveShadow position={[-23.77, 61.5, -7.54]} />
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={4.03}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-111.5385}
            shadow-camera-right={111.5385}
            shadow-camera-top={111.5385}
            shadow-camera-bottom={-111.5385}
            color="#d6b9fe"
            position={[-509, 300, 300]}
          />
          <OrthographicCamera name="1" makeDefault={false} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={2.54} color="#eaeaea" />
        </scene>
      </group>
    </>
  );
}
